name: 'Build and deploy JAR app to Azure Web App: movtotrackzone-rm554764'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Checkout do reposit√≥rio
      - uses: actions/checkout@v2

      # Passo 2: Configurar Java 17
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Passo 3: Build com Maven ignorando testes
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./universidade_fiap
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      # Passo 4: Deploy no Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'movtotrackzone-rm554764'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f10b9cba95544bd850a070094e6e8a7 }}
          package: '${{ github.workspace }}/universidade_fiap/target/*.jar'
